kind: Service
apiVersion: v1
metadata:
  name: learnmui-app-service
  labels:
    app: learnmui-app-service
spec:
  type: ClusterIP
  selector:
    app: learnmui-app-deployment
  ports:
    - port: 8090
      targetPort: 8090
