name: Build and Deploy
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/*'
      - 'packages/mui-admin-board/**'
      - 'packages/learn-typescript/**'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Path fiters
        id: path_filters
        uses: dorny/paths-filter@v2
        with:
          filters: |
            learn-typescript:
              - 'packages/learn-typescript/**'
            mui-admin-board:
              - 'packages/mui-admin-board/**'

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push learn-mui-adminboard
        if: steps.path_filters.outputs.mui-admin-board == 'true'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./packages/mui-admin-board/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/cloudlifter-images:learn-mui-adminboard

      - name: Just to Debug
        run: |
          echo "${{toJSON(steps)}}"
