name: Build and Deploy
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/*'
      - 'packages/mui-admin-board/**'
      - 'packages/learn-typescript/**'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
          cd packages/mui-admin-board && yarn install --frozen-lockfile
          cd ../learn-typescript && yarn install --frozen-lockfile

      - name: Path fiters
        id: path_filters
        uses: dorny/paths-filter@v2
        with:
          filters: |
            learn-typescript:
              - 'packages/learn-typescript/**'
            mui-admin-board:
              - 'packages/mui-admin-board/**'

      - name: Just to Debug
        run: |
          echo "${{toJSON(steps)}}"

      - name: Build React frontend
        if: steps.path_filters.outputs.mui-admin-board == 'true'
        working-directory: ./packages/mui-admin-board
        run: yarn build

      - name: Build Express backend
        if: steps.path_filters.outputs.learn-typescript == 'true'
        working-directory: ./packages/learn-typescript
        run: yarn build
